# Generated by Praetor from declared project commands; execution is unverified.
# Praetor ships one binary under two names; resolve whichever is installed.
PRAETORCTL ?= $(shell command -v praetorctl 2>/dev/null || command -v standardsctl 2>/dev/null || echo praetorctl)
.PHONY: all verify-all compile-context compile-context-verify caveman-sources audit build test

all: build

verify-all: compile-context-verify caveman-sources audit test

compile-context:
	@$(PRAETORCTL) compile-context

compile-context-verify:
	@$(PRAETORCTL) compile-context --verify

caveman-sources:
	@$(PRAETORCTL) caveman check --configured-sources

audit:
	@$(PRAETORCTL) audit

test: build
	@exec 'go' 'test' '-v' '-race' './...'

build:
	@exec 'go' 'build' '-v' './...'

# BEGIN praetor documentation gate
.PHONY: docs-lint docs-figures
verify-all: docs-lint docs-figures
docs-lint:
	@node tools/markdownlint/verify.mjs
docs-figures:
	@node tools/figures/build.mjs check
	@node tools/figures/build.mjs sources
# END praetor documentation gate

.PHONY: schemas-refresh schemas-check
schemas-refresh:
	@go run -tags schemasrefresh ./tools/schemas -mode=refresh -root=. -out=.

schemas-check:
	@go run -tags schemasrefresh ./tools/schemas -mode=check -root=.
