// Provenance:
// Source URL: https://raw.githubusercontent.com/openai/codex/2351d9e1b608e6f9d9a3699b71d7eb39ee41cfa4/codex-rs/codex-backend-openapi-models/src/models/rate_limit_status_details.rs
// Pinned revision: 2351d9e1b608e6f9d9a3699b71d7eb39ee41cfa4
// Full document sha256: 38935bb0f24cbb60bb9def3426fdd44bdec75dee92d8c0396698e851f122c00a
// Extraction date: 2026-10-09
// SPDX licence: Apache-2.0
// Copyright holder: OpenAI
// Changes: provenance header added by Tribunus; extracted the pinned Codex source file verbatim

/*
 * codex-backend
 *
 * codex-backend
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::Deserialize;
use serde::Serialize;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RateLimitStatusDetails {
    #[serde(rename = "allowed")]
    pub allowed: bool,
    #[serde(rename = "limit_reached")]
    pub limit_reached: bool,
    #[serde(
        rename = "primary_window",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub primary_window: Option<Option<Box<models::RateLimitWindowSnapshot>>>,
    #[serde(
        rename = "secondary_window",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub secondary_window: Option<Option<Box<models::RateLimitWindowSnapshot>>>,
}

impl RateLimitStatusDetails {
    pub fn new(allowed: bool, limit_reached: bool) -> RateLimitStatusDetails {
        RateLimitStatusDetails {
            allowed,
            limit_reached,
            primary_window: None,
            secondary_window: None,
        }
    }
}
