// Provenance:
// Source URL: https://raw.githubusercontent.com/openai/codex/2351d9e1b608e6f9d9a3699b71d7eb39ee41cfa4/codex-rs/codex-backend-openapi-models/src/models/rate_limit_window_snapshot.rs
// Pinned revision: 2351d9e1b608e6f9d9a3699b71d7eb39ee41cfa4
// Full document sha256: f667756c00e512c779cb0f593737094b1292990494624492f0c0bb48dcd6918b
// Extraction date: 2026-10-09
// SPDX licence: Apache-2.0
// Copyright holder: OpenAI
// Changes: provenance header added by Tribunus; extracted the pinned Codex source file verbatim

/*
 * codex-backend
 *
 * codex-backend
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 */
use serde::Deserialize;
use serde::Serialize;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RateLimitWindowSnapshot {
    #[serde(rename = "used_percent")]
    pub used_percent: i32,
    #[serde(rename = "limit_window_seconds")]
    pub limit_window_seconds: i32,
    #[serde(rename = "reset_after_seconds")]
    pub reset_after_seconds: i32,
    #[serde(rename = "reset_at")]
    pub reset_at: i32,
}

impl RateLimitWindowSnapshot {
    pub fn new(
        used_percent: i32,
        limit_window_seconds: i32,
        reset_after_seconds: i32,
        reset_at: i32,
    ) -> RateLimitWindowSnapshot {
        RateLimitWindowSnapshot {
            used_percent,
            limit_window_seconds,
            reset_after_seconds,
            reset_at,
        }
    }
}
